log    =    log/$(Cluster)_$(Process).log
error  =  error/$(Cluster)_$(Process).err

universe = vanilla

executable = ./part1_post.sh
arguments = postCovid $(Process)

should_transfer_files = YES
when_to_transfer_output = ON_EXIT
transfer_input_files = python39.tar.gz, PythonPackages.tar.gz, read.py, R413.tar.gz, packages_FITSio_tidyverse.tar.gz, process.R, postCovid, regression.R

request_cpus = 12
request_memory = 100GB
request_disk = 10GB

queue 1
